apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-e5ja
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jnowakos-tenant/my-app/devfile-sample-code-with-quarkus-e5ja@sha256:8d13b27b964d57a8d4b38dc2b5443d5f041fca4cacf1b20ee21cc9a020d8ecb0
        name: my-java-quarkus
        resources: {}
status: {}
